export interface Wordpair {
    wordOne: string;
    wordTwo: string;
}

export const wordPairs: Wordpair[] = [
    { wordOne: 'Meer', wordTwo: 'Ozean' },
    { wordOne: 'Tasse', wordTwo: 'Becher' },
    { wordOne: 'Auto', wordTwo: 'Kraftfahrzeug' },
    { wordOne: 'Haus', wordTwo: 'Zuhause' },
    { wordOne: 'Katze', wordTwo: 'Kätzchen' },
    { wordOne: 'Hund', wordTwo: 'Welpe' },
    { wordOne: 'Buch', wordTwo: 'Roman' },
    { wordOne: 'Stuhl', wordTwo: 'Sitz' },
    { wordOne: 'Berg', wordTwo: 'Hügel' },
    { wordOne: 'Fluss', wordTwo: 'Strom' },
    { wordOne: 'Hut', wordTwo: 'Kappe' },
    { wordOne: 'Fahrrad', wordTwo: 'Rad' },
    { wordOne: 'Baum', wordTwo: 'Pflanze' },
    { wordOne: 'Löffel', wordTwo: 'Gabel' },
    { wordOne: 'Flugzeug', wordTwo: 'Luftfahrzeug' },
    { wordOne: 'Sonne', wordTwo: 'Stern' },
    { wordOne: 'Hemd', wordTwo: 'Bluse' },
    { wordOne: 'Stift', wordTwo: 'Bleistift' },
    { wordOne: 'Insel', wordTwo: 'Halbinsel' },
    { wordOne: 'Mütze', wordTwo: 'Kappe' },
    { wordOne: 'Mond', wordTwo: 'Satellit' },
    { wordOne: 'Film', wordTwo: 'Film' },
    { wordOne: 'Socke', wordTwo: 'Strumpf' },
    { wordOne: 'Bus', wordTwo: 'Reisebus' },
    { wordOne: 'Regen', wordTwo: 'Schauer' },
    { wordOne: 'Brücke', wordTwo: 'Viadukt' },
    { wordOne: 'Handschuh', wordTwo: 'Fausthandschuh' },
    { wordOne: 'Obst', wordTwo: 'Beere' },
    { wordOne: 'Restaurant', wordTwo: 'Café' },
    { wordOne: 'Zug', wordTwo: 'Lokomotive' },
    { wordOne: 'Radio', wordTwo: 'Fernseher' },
    { wordOne: 'Jacke', wordTwo: 'Mantel' },
    { wordOne: 'Wohnung', wordTwo: 'Wohnung' },
    { wordOne: 'Kuh', wordTwo: 'Rind' },
    { wordOne: 'Tastatur', wordTwo: 'Zahlentastatur' },
    { wordOne: 'Hut', wordTwo: 'Mütze' },
    { wordOne: 'See', wordTwo: 'Teich' },
    { wordOne: 'Dorf', wordTwo: 'Stadt' },
    { wordOne: 'Blatt', wordTwo: 'Blütenblatt' },
    { wordOne: 'Teppich', wordTwo: 'Teppichboden' },
    { wordOne: 'Baby', wordTwo: 'Säugling' },
    { wordOne: 'Hotel', wordTwo: 'Gasthaus' },
    { wordOne: 'Fluss', wordTwo: 'Bach' },
    { wordOne: 'Vogel', wordTwo: 'Gefiedertes Tier' },
    { wordOne: 'Berg', wordTwo: 'Gipfel' },
    { wordOne: 'Haus', wordTwo: 'Gebäude' },
    { wordOne: 'Ozean', wordTwo: 'Meer' },
    { wordOne: 'Schuh', wordTwo: 'Turnschuh' },
    { wordOne: 'Blume', wordTwo: 'Blüte' },
    { wordOne: 'Auto', wordTwo: 'Fahrzeug' }
];